name: 'moia-oss/aws-codepipeline-trigger'
description: 'Trigger an AWS CodePipeline from GitHub Actions'
inputs:
  pipeline:
    description: 'The name of the CodePipeline'
    required: true
  wait:
    description: 'Wait for the CodePipeline to finish and exit with same result as the CodePipeline'
    required: false
    default: false
  follow-codebuild:
    description: 'This controls whether CodeBuild Logs will be forwarded to GitHub Actions'
    required: false
    default: false
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'cloud'
  color: 'orange'
