name: Renovate Check

on:
  push:
    branches: [ master ]
    paths:
      - '.github/**'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/**'

env:
  LOG_LEVEL: debug

jobs:
  check-renovate-configuration:
    uses: moia-dev/github-workflows/.github/workflows/renovate-check.yml@main
